// Export Utilities for Chunking Results
import type { ChunkingResult, ChunkingStrategyType, Document } from '@/types';

interface ExportOptions {
    document?: Document;
    strategy: ChunkingStrategyType;
    result: ChunkingResult;
}

// Get strategy display name
function getStrategyName(strategyId: ChunkingStrategyType): string {
    const names: Record<ChunkingStrategyType, string> = {
        'fixed-size': 'Tamaño Fijo (Fixed-Size)',
        'semantic': 'Semántico (Semantic)',
        'recursive': 'Recursivo (Recursive)',
        'document-structure': 'Estructura de Documento (Document-Structure)',
        'llm-based': 'Basado en LLM (LLM-Based)',
    };
    return names[strategyId] || strategyId;
}

// Format config object as readable text
function formatConfig(config: Record<string, unknown>): string {
    return Object.entries(config)
        .map(([key, value]) => {
            // Format key from camelCase to Title Case
            const formattedKey = key
                .replace(/([A-Z])/g, ' $1')
                .replace(/^./, (str) => str.toUpperCase())
                .trim();
            return `  - ${formattedKey}: ${value}`;
        })
        .join('\n');
}

// Export to Markdown format
export function exportToMarkdown({ document, strategy, result }: ExportOptions): string {
    const strategyName = getStrategyName(strategy);
    const timestamp = new Date().toLocaleString();
    const stats = result.statistics;

    let markdown = `# Chunking Results - ${strategyName}\n\n`;

    // Document info
    if (document) {
        markdown += `**Document:** ${document.name}\n`;
        markdown += `**Size:** ${(document.size / 1024).toFixed(1)} KB\n`;
        markdown += `**Type:** ${document.type.toUpperCase()}\n`;
    }
    markdown += `**Exported:** ${timestamp}\n\n`;

    markdown += `---\n\n`;

    // Strategy info
    markdown += `## Strategy: ${strategyName}\n\n`;
    markdown += `**Configuration:**\n`;
    markdown += formatConfig(result.config);
    markdown += `\n\n`;

    // Statistics
    markdown += `## Statistics\n\n`;
    markdown += `- **Total Chunks:** ${stats.totalChunks}\n`;
    markdown += `- **Average Size:** ${stats.averageChunkSize} characters\n`;
    markdown += `- **Min Size:** ${stats.minChunkSize} characters\n`;
    markdown += `- **Max Size:** ${stats.maxChunkSize} characters\n`;
    if (stats.totalTokens) {
        markdown += `- **Total Tokens:** ${stats.totalTokens}\n`;
    }
    if (stats.overlapPercentage !== undefined) {
        markdown += `- **Overlap:** ${stats.overlapPercentage.toFixed(1)}%\n`;
    }
    markdown += `- **Processing Time:** ${result.processingTime.toFixed(1)}ms\n\n`;

    markdown += `---\n\n`;

    // Chunks
    markdown += `## Chunks (${result.chunks.length})\n\n`;

    result.chunks.forEach((chunk, index) => {
        markdown += `### Chunk ${index + 1} (ID: ${chunk.id})\n\n`;
        markdown += `**Position:** ${chunk.startIndex}-${chunk.endIndex}\n`;
        markdown += `**Size:** ${chunk.text.length} characters\n`;

        // Add strategy-specific metadata
        if (chunk.metadata.sentenceCount) {
            markdown += `**Sentences:** ${chunk.metadata.sentenceCount}\n`;
        }
        if (chunk.metadata.sectionTitle) {
            markdown += `**Section:** ${chunk.metadata.sectionTitle}\n`;
        }
        if (chunk.metadata.level) {
            markdown += `**Level:** ${chunk.metadata.level}\n`;
        }

        markdown += `\n\`\`\`\n${chunk.text}\n\`\`\`\n\n`;

        // Add separator between chunks (except last one)
        if (index < result.chunks.length - 1) {
            markdown += `---\n\n`;
        }
    });

    // Footer
    markdown += `\n---\n\n`;
    markdown += `*Generated by RAG Chunking Visualizer*\n`;
    markdown += `*🤖 Powered by Claude Code - [claude.com/code](https://claude.com/code)*\n`;

    return markdown;
}

// Download markdown file
export function downloadMarkdown(markdown: string, filename: string): void {
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

// Copy to clipboard
export async function copyToClipboard(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch (error) {
        console.error('Failed to copy to clipboard:', error);
        // Fallback for older browsers
        try {
            const textarea = document.createElement('textarea');
            textarea.value = text;
            textarea.style.position = 'fixed';
            textarea.style.opacity = '0';
            document.body.appendChild(textarea);
            textarea.select();
            const success = document.execCommand('copy');
            document.body.removeChild(textarea);
            return success;
        } catch (fallbackError) {
            console.error('Fallback copy failed:', fallbackError);
            return false;
        }
    }
}

// Generate filename from strategy and timestamp
export function generateFilename(strategy: ChunkingStrategyType, documentName?: string): string {
    const timestamp = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    const docPart = documentName ? documentName.replace(/\.[^/.]+$/, '') : 'document';
    const sanitizedDoc = docPart.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    return `chunking_${sanitizedDoc}_${strategy}_${timestamp}.md`;
}
