name = "chunking-strats-in-action"
compatibility_date = "2024-04-03"
compatibility_flags = [ "nodejs_compat" ]

# No necesitamos [site] para Cloudflare Pages
# La configuración del directorio se hace en el dashboard o mediante [pages]

